[package]
name = "artbox"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui = "0.29"
rusqlite = "0.29"
serde = { version = "1.0", features = ["derive"] } # "1.0.160"
serde_json = "1.0"
directories = "5.0"
